{
    "Frequency": "SINGLE",
    "InstrToken": "",
    "Version": "1.1",
    "MerchantID": "",
    "Language": "EN",
    "TxnType": "MPAY",
    "SubMerchant": "",
    "Password": null,
    "TxnRef": "<?php echo(json_encode($_TxnRefNumber)); ?>",
    "Amount": "<?php echo(json_encode($_AmountTmp)); ?>",
    "DiscountedAmount": "",
    "DiscountBank": "",
    "TxnCurrency": "PKR",
    "TxnDate": "<?php echo(json_encode($TxnDateTime)); ?>",
    "TxnExpiry": "",
    "BillReference": "ref bill",
    "Description": "Hello",
    "ReturnURL": null,
    "mpf_1": "",
    "mpf_2": "",
    "mpf_3": "",
    "mpf_4": "",
    "mpf_5": "",
    "SecureHash": ""
}